name: Fabriquer EXE

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les librairies et PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Créer l'EXE
        run: |
          pyinstaller --onefile --windowed --name shippings_labels pdf_extraction_v1.py

      - name: Vérifier le dossier dist
        run: dir dist

      - name: Télécharger le résultat
        uses: actions/upload-artifact@v4
        with:
          name: MonApplicationWindows
          path: dist/
